apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\pansica\docker-docs\docker-webapp\docker-compose\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\pansica\docker-docs\docker-webapp\docker-compose\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: OBJECTDB_PASSWORD
          value: password
        image: diegopansica/objectdb:2.8.4
        imagePullPolicy: ""
        name: database
        ports:
        - containerPort: 6136
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
