apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\pansica\docker-docs\docker-webapp\docker-compose\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
  - name: "6136"
    port: 6136
    targetPort: 6136
  selector:
    io.kompose.service: database
status:
  loadBalancer: {}
