apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\pansica\docker-docs\docker-webapp\docker-compose\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: webnode
  name: webnode
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    io.kompose.service: webnode
status:
  loadBalancer: {}
